// Mocks generated by Mockito 5.4.6 from annotations
// in node_graph_notebook/test/plugins/lua/service/lua_api_implementation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:node_graph_notebook/core/models/models.dart' as _i2;
import 'package:node_graph_notebook/core/repositories/graph_repository.dart'
    as _i8;
import 'package:node_graph_notebook/core/repositories/node_repository.dart'
    as _i5;
import 'package:node_graph_notebook/plugins/lua/models/lua_execution_result.dart'
    as _i4;
import 'package:node_graph_notebook/plugins/lua/service/lua_engine_service.dart'
    as _i9;
import 'package:node_graph_notebook/plugins/lua/service/lua_security_manager.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMetadataIndex_0 extends _i1.SmartFake implements _i2.MetadataIndex {
  _FakeMetadataIndex_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGraph_1 extends _i1.SmartFake implements _i2.Graph {
  _FakeGraph_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLuaSecurityManager_2 extends _i1.SmartFake
    implements _i3.LuaSecurityManager {
  _FakeLuaSecurityManager_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLuaExecutionResult_3 extends _i1.SmartFake
    implements _i4.LuaExecutionResult {
  _FakeLuaExecutionResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeRepository extends _i1.Mock implements _i5.NodeRepository {
  MockNodeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> save(_i2.Node? node) =>
      (super.noSuchMethod(
            Invocation.method(#save, [node]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.Node?> load(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#load, [nodeId]),
            returnValue: _i6.Future<_i2.Node?>.value(),
          )
          as _i6.Future<_i2.Node?>);

  @override
  _i6.Future<void> delete(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [nodeId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveAll(List<_i2.Node>? nodes) =>
      (super.noSuchMethod(
            Invocation.method(#saveAll, [nodes]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.Node>> loadAll(List<String>? nodeIds) =>
      (super.noSuchMethod(
            Invocation.method(#loadAll, [nodeIds]),
            returnValue: _i6.Future<List<_i2.Node>>.value(<_i2.Node>[]),
          )
          as _i6.Future<List<_i2.Node>>);

  @override
  _i6.Future<List<_i2.Node>> queryAll() =>
      (super.noSuchMethod(
            Invocation.method(#queryAll, []),
            returnValue: _i6.Future<List<_i2.Node>>.value(<_i2.Node>[]),
          )
          as _i6.Future<List<_i2.Node>>);

  @override
  _i6.Future<List<_i2.Node>> search({
    String? title,
    String? content,
    List<String>? tags,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [], {
              #title: title,
              #content: content,
              #tags: tags,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i6.Future<List<_i2.Node>>.value(<_i2.Node>[]),
          )
          as _i6.Future<List<_i2.Node>>);

  @override
  String getNodeFilePath(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getNodeFilePath, [nodeId]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getNodeFilePath, [nodeId]),
            ),
          )
          as String);

  @override
  _i6.Future<_i2.MetadataIndex> getMetadataIndex() =>
      (super.noSuchMethod(
            Invocation.method(#getMetadataIndex, []),
            returnValue: _i6.Future<_i2.MetadataIndex>.value(
              _FakeMetadataIndex_0(
                this,
                Invocation.method(#getMetadataIndex, []),
              ),
            ),
          )
          as _i6.Future<_i2.MetadataIndex>);

  @override
  _i6.Future<void> updateIndex(_i2.Node? node) =>
      (super.noSuchMethod(
            Invocation.method(#updateIndex, [node]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [GraphRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphRepository extends _i1.Mock implements _i8.GraphRepository {
  MockGraphRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> save(_i2.Graph? graph) =>
      (super.noSuchMethod(
            Invocation.method(#save, [graph]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.Graph?> load(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#load, [graphId]),
            returnValue: _i6.Future<_i2.Graph?>.value(),
          )
          as _i6.Future<_i2.Graph?>);

  @override
  _i6.Future<void> delete(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [graphId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.Graph>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i6.Future<List<_i2.Graph>>.value(<_i2.Graph>[]),
          )
          as _i6.Future<List<_i2.Graph>>);

  @override
  _i6.Future<_i2.Graph?> getCurrent() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrent, []),
            returnValue: _i6.Future<_i2.Graph?>.value(),
          )
          as _i6.Future<_i2.Graph?>);

  @override
  _i6.Future<void> setCurrent(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrent, [graphId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> export(String? graphId, String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#export, [graphId, filePath]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.Graph> import(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#import, [filePath]),
            returnValue: _i6.Future<_i2.Graph>.value(
              _FakeGraph_1(this, Invocation.method(#import, [filePath])),
            ),
          )
          as _i6.Future<_i2.Graph>);
}

/// A class which mocks [LuaEngineService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLuaEngineService extends _i1.Mock implements _i9.LuaEngineService {
  MockLuaEngineService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.LuaEngineType get engineType =>
      (super.noSuchMethod(
            Invocation.getter(#engineType),
            returnValue: _i9.LuaEngineType.simple,
          )
          as _i9.LuaEngineType);

  @override
  bool get enableSandbox =>
      (super.noSuchMethod(Invocation.getter(#enableSandbox), returnValue: false)
          as bool);

  @override
  bool get enableDebugOutput =>
      (super.noSuchMethod(
            Invocation.getter(#enableDebugOutput),
            returnValue: false,
          )
          as bool);

  @override
  _i3.LuaSecurityManager get securityManager =>
      (super.noSuchMethod(
            Invocation.getter(#securityManager),
            returnValue: _FakeLuaSecurityManager_2(
              this,
              Invocation.getter(#securityManager),
            ),
          )
          as _i3.LuaSecurityManager);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.LuaExecutionResult> executeString(
    String? script, {
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#executeString, [script], {#context: context}),
            returnValue: _i6.Future<_i4.LuaExecutionResult>.value(
              _FakeLuaExecutionResult_3(
                this,
                Invocation.method(
                  #executeString,
                  [script],
                  {#context: context},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.LuaExecutionResult>);

  @override
  _i6.Future<_i4.LuaExecutionResult> executeFile(
    String? filePath, {
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#executeFile, [filePath], {#context: context}),
            returnValue: _i6.Future<_i4.LuaExecutionResult>.value(
              _FakeLuaExecutionResult_3(
                this,
                Invocation.method(
                  #executeFile,
                  [filePath],
                  {#context: context},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.LuaExecutionResult>);

  @override
  void registerFunction(String? name, _i9.DartFunctionCallback? fn) =>
      super.noSuchMethod(
        Invocation.method(#registerFunction, [name, fn]),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> reset() =>
      (super.noSuchMethod(
            Invocation.method(#reset, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.LuaExecutionResult> invokeCallback(
    String? callbackName,
    List<dynamic>? args,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#invokeCallback, [callbackName, args]),
            returnValue: _i6.Future<_i4.LuaExecutionResult>.value(
              _FakeLuaExecutionResult_3(
                this,
                Invocation.method(#invokeCallback, [callbackName, args]),
              ),
            ),
          )
          as _i6.Future<_i4.LuaExecutionResult>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
