// Mocks generated by Mockito 5.4.6 from annotations
// in node_graph_notebook/test/plugins/lua/handler/execute_lua_script_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:node_graph_notebook/plugins/lua/models/lua_execution_result.dart'
    as _i3;
import 'package:node_graph_notebook/plugins/lua/models/lua_script.dart' as _i7;
import 'package:node_graph_notebook/plugins/lua/service/lua_engine_service.dart'
    as _i4;
import 'package:node_graph_notebook/plugins/lua/service/lua_script_service.dart'
    as _i6;
import 'package:node_graph_notebook/plugins/lua/service/lua_security_manager.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLuaSecurityManager_0 extends _i1.SmartFake
    implements _i2.LuaSecurityManager {
  _FakeLuaSecurityManager_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLuaExecutionResult_1 extends _i1.SmartFake
    implements _i3.LuaExecutionResult {
  _FakeLuaExecutionResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LuaEngineService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLuaEngineService extends _i1.Mock implements _i4.LuaEngineService {
  MockLuaEngineService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.LuaEngineType get engineType =>
      (super.noSuchMethod(
            Invocation.getter(#engineType),
            returnValue: _i4.LuaEngineType.simple,
          )
          as _i4.LuaEngineType);

  @override
  bool get enableSandbox =>
      (super.noSuchMethod(Invocation.getter(#enableSandbox), returnValue: false)
          as bool);

  @override
  bool get enableDebugOutput =>
      (super.noSuchMethod(
            Invocation.getter(#enableDebugOutput),
            returnValue: false,
          )
          as bool);

  @override
  _i2.LuaSecurityManager get securityManager =>
      (super.noSuchMethod(
            Invocation.getter(#securityManager),
            returnValue: _FakeLuaSecurityManager_0(
              this,
              Invocation.getter(#securityManager),
            ),
          )
          as _i2.LuaSecurityManager);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.LuaExecutionResult> executeString(
    String? script, {
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#executeString, [script], {#context: context}),
            returnValue: _i5.Future<_i3.LuaExecutionResult>.value(
              _FakeLuaExecutionResult_1(
                this,
                Invocation.method(
                  #executeString,
                  [script],
                  {#context: context},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.LuaExecutionResult>);

  @override
  _i5.Future<_i3.LuaExecutionResult> executeFile(
    String? filePath, {
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#executeFile, [filePath], {#context: context}),
            returnValue: _i5.Future<_i3.LuaExecutionResult>.value(
              _FakeLuaExecutionResult_1(
                this,
                Invocation.method(
                  #executeFile,
                  [filePath],
                  {#context: context},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.LuaExecutionResult>);

  @override
  void registerFunction(String? name, _i4.DartFunctionCallback? fn) =>
      super.noSuchMethod(
        Invocation.method(#registerFunction, [name, fn]),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> reset() =>
      (super.noSuchMethod(
            Invocation.method(#reset, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.LuaExecutionResult> invokeCallback(
    String? callbackName,
    List<dynamic>? args,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#invokeCallback, [callbackName, args]),
            returnValue: _i5.Future<_i3.LuaExecutionResult>.value(
              _FakeLuaExecutionResult_1(
                this,
                Invocation.method(#invokeCallback, [callbackName, args]),
              ),
            ),
          )
          as _i5.Future<_i3.LuaExecutionResult>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [LuaScriptService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLuaScriptService extends _i1.Mock implements _i6.LuaScriptService {
  MockLuaScriptService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.LuaScript>> loadAllScripts() =>
      (super.noSuchMethod(
            Invocation.method(#loadAllScripts, []),
            returnValue: _i5.Future<List<_i7.LuaScript>>.value(
              <_i7.LuaScript>[],
            ),
          )
          as _i5.Future<List<_i7.LuaScript>>);

  @override
  _i5.Future<void> saveScript(_i7.LuaScript? script) =>
      (super.noSuchMethod(
            Invocation.method(#saveScript, [script]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteScript(String? scriptId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteScript, [scriptId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> enableScript(String? scriptId) =>
      (super.noSuchMethod(
            Invocation.method(#enableScript, [scriptId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> disableScript(String? scriptId) =>
      (super.noSuchMethod(
            Invocation.method(#disableScript, [scriptId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i7.LuaScript? getScriptInfo(String? scriptId) =>
      (super.noSuchMethod(Invocation.method(#getScriptInfo, [scriptId]))
          as _i7.LuaScript?);

  @override
  List<_i7.LuaScript> getEnabledScripts() =>
      (super.noSuchMethod(
            Invocation.method(#getEnabledScripts, []),
            returnValue: <_i7.LuaScript>[],
          )
          as List<_i7.LuaScript>);

  @override
  List<_i7.LuaScript> getAllScripts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllScripts, []),
            returnValue: <_i7.LuaScript>[],
          )
          as List<_i7.LuaScript>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
