// Mocks generated by Mockito 5.4.6 from annotations
// in node_graph_notebook/test/plugins/graph/handler/create_node_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:node_graph_notebook/core/commands/models/command_context.dart'
    as _i6;
import 'package:node_graph_notebook/core/events/app_events.dart' as _i3;
import 'package:node_graph_notebook/core/models/models.dart' as _i2;
import 'package:node_graph_notebook/core/repositories/repositories.dart' as _i4;
import 'package:node_graph_notebook/plugins/graph/service/node_service.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNode_0 extends _i1.SmartFake implements _i2.Node {
  _FakeNode_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppEventBus_1 extends _i1.SmartFake implements _i3.AppEventBus {
  _FakeAppEventBus_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNodeRepository_2 extends _i1.SmartFake
    implements _i4.NodeRepository {
  _FakeNodeRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGraphRepository_3 extends _i1.SmartFake
    implements _i4.GraphRepository {
  _FakeGraphRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_4<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommandContext_5 extends _i1.SmartFake
    implements _i6.CommandContext {
  _FakeCommandContext_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NodeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeService extends _i1.Mock implements _i7.NodeService {
  MockNodeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Node> createNode({
    required String? title,
    String? content,
    _i8.Offset? position,
    _i8.Size? size,
    String? color,
    Map<String, _i2.NodeReference>? references,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createNode, [], {
              #title: title,
              #content: content,
              #position: position,
              #size: size,
              #color: color,
              #references: references,
              #metadata: metadata,
            }),
            returnValue: _i5.Future<_i2.Node>.value(
              _FakeNode_0(
                this,
                Invocation.method(#createNode, [], {
                  #title: title,
                  #content: content,
                  #position: position,
                  #size: size,
                  #color: color,
                  #references: references,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Node>);

  @override
  _i5.Future<_i2.Node> updateNode(
    String? nodeId, {
    String? title,
    String? content,
    _i8.Offset? position,
    _i8.Size? size,
    _i2.NodeViewMode? viewMode,
    String? color,
    Map<String, _i2.NodeReference>? references,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateNode,
              [nodeId],
              {
                #title: title,
                #content: content,
                #position: position,
                #size: size,
                #viewMode: viewMode,
                #color: color,
                #references: references,
                #metadata: metadata,
              },
            ),
            returnValue: _i5.Future<_i2.Node>.value(
              _FakeNode_0(
                this,
                Invocation.method(
                  #updateNode,
                  [nodeId],
                  {
                    #title: title,
                    #content: content,
                    #position: position,
                    #size: size,
                    #viewMode: viewMode,
                    #color: color,
                    #references: references,
                    #metadata: metadata,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Node>);

  @override
  _i5.Future<void> deleteNode(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNode, [nodeId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Node?> getNode(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getNode, [nodeId]),
            returnValue: _i5.Future<_i2.Node?>.value(),
          )
          as _i5.Future<_i2.Node?>);

  @override
  _i5.Future<List<_i2.Node>> getAllNodes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNodes, []),
            returnValue: _i5.Future<List<_i2.Node>>.value(<_i2.Node>[]),
          )
          as _i5.Future<List<_i2.Node>>);

  @override
  _i5.Future<List<_i2.Node>> searchNodes(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchNodes, [query]),
            returnValue: _i5.Future<List<_i2.Node>>.value(<_i2.Node>[]),
          )
          as _i5.Future<List<_i2.Node>>);

  @override
  _i5.Future<void> connectNodes({
    required String? fromNodeId,
    required String? toNodeId,
    Map<String, dynamic>? properties,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#connectNodes, [], {
              #fromNodeId: fromNodeId,
              #toNodeId: toNodeId,
              #properties: properties,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> disconnectNodes({
    required String? fromNodeId,
    required String? toNodeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectNodes, [], {
              #fromNodeId: fromNodeId,
              #toNodeId: toNodeId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> batchUpdate(List<_i7.NodeUpdate>? updates) =>
      (super.noSuchMethod(
            Invocation.method(#batchUpdate, [updates]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> batchDelete(List<String>? nodeIds) =>
      (super.noSuchMethod(
            Invocation.method(#batchDelete, [nodeIds]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, int>> calculateNodeDepths(List<_i2.Node>? nodes) =>
      (super.noSuchMethod(
            Invocation.method(#calculateNodeDepths, [nodes]),
            returnValue: _i5.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i5.Future<Map<String, int>>);
}

/// A class which mocks [CommandContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommandContext extends _i1.Mock implements _i6.CommandContext {
  MockCommandContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AppEventBus get eventBus =>
      (super.noSuchMethod(
            Invocation.getter(#eventBus),
            returnValue: _FakeAppEventBus_1(this, Invocation.getter(#eventBus)),
          )
          as _i3.AppEventBus);

  @override
  _i4.NodeRepository get nodeRepository =>
      (super.noSuchMethod(
            Invocation.getter(#nodeRepository),
            returnValue: _FakeNodeRepository_2(
              this,
              Invocation.getter(#nodeRepository),
            ),
          )
          as _i4.NodeRepository);

  @override
  _i4.GraphRepository get graphRepository =>
      (super.noSuchMethod(
            Invocation.getter(#graphRepository),
            returnValue: _FakeGraphRepository_3(
              this,
              Invocation.getter(#graphRepository),
            ),
          )
          as _i4.GraphRepository);

  @override
  bool get isInTransaction =>
      (super.noSuchMethod(
            Invocation.getter(#isInTransaction),
            returnValue: false,
          )
          as bool);

  @override
  set eventBus(_i3.AppEventBus? value) => super.noSuchMethod(
    Invocation.setter(#eventBus, value),
    returnValueForMissingStub: null,
  );

  @override
  void publishNodeEvent(List<_i2.Node>? nodes, _i3.DataChangeAction? action) =>
      super.noSuchMethod(
        Invocation.method(#publishNodeEvent, [nodes, action]),
        returnValueForMissingStub: null,
      );

  @override
  void publishSingleNodeEvent(_i2.Node? node, _i3.DataChangeAction? action) =>
      super.noSuchMethod(
        Invocation.method(#publishSingleNodeEvent, [node, action]),
        returnValueForMissingStub: null,
      );

  @override
  void publishGraphRelationEvent(
    String? graphId,
    List<String>? nodeIds,
    _i3.RelationChangeAction? action,
  ) => super.noSuchMethod(
    Invocation.method(#publishGraphRelationEvent, [graphId, nodeIds, action]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<T> withTransaction<T>(_i5.Future<T> Function()? operation) =>
      (super.noSuchMethod(
            Invocation.method(#withTransaction, [operation]),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#withTransaction, [operation]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_4<T>(
                  this,
                  Invocation.method(#withTransaction, [operation]),
                ),
          )
          as _i5.Future<T>);

  @override
  _i3.AppEventBus getAppEventBus() =>
      (super.noSuchMethod(
            Invocation.method(#getAppEventBus, []),
            returnValue: _FakeAppEventBus_1(
              this,
              Invocation.method(#getAppEventBus, []),
            ),
          )
          as _i3.AppEventBus);

  @override
  void registerService<T>(T? service) => super.noSuchMethod(
    Invocation.method(#registerService, [service]),
    returnValueForMissingStub: null,
  );

  @override
  T read<T>() =>
      (super.noSuchMethod(
            Invocation.method(#read, []),
            returnValue: _i9.dummyValue<T>(this, Invocation.method(#read, [])),
          )
          as T);

  @override
  void setMetadata(String? key, dynamic value) => super.noSuchMethod(
    Invocation.method(#setMetadata, [key, value]),
    returnValueForMissingStub: null,
  );

  @override
  dynamic getMetadata(String? key) =>
      super.noSuchMethod(Invocation.method(#getMetadata, [key]));

  @override
  bool hasMetadata(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#hasMetadata, [key]),
            returnValue: false,
          )
          as bool);

  @override
  void clearMetadata() => super.noSuchMethod(
    Invocation.method(#clearMetadata, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.CommandContext createChild() =>
      (super.noSuchMethod(
            Invocation.method(#createChild, []),
            returnValue: _FakeCommandContext_5(
              this,
              Invocation.method(#createChild, []),
            ),
          )
          as _i6.CommandContext);
}
