// Mocks generated by Mockito 5.4.6 from annotations
// in node_graph_notebook/test/plugins/converter/bloc/converter_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:node_graph_notebook/core/models/models.dart' as _i6;
import 'package:node_graph_notebook/plugins/converter/models/models.dart'
    as _i2;
import 'package:node_graph_notebook/plugins/converter/service/import_export_service.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConversionResult_0 extends _i1.SmartFake
    implements _i2.ConversionResult {
  _FakeConversionResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_1 extends _i1.SmartFake implements _i3.File {
  _FakeFile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ImportExportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImportExportService extends _i1.Mock
    implements _i4.ImportExportService {
  MockImportExportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.Node>> previewImport({
    required String? filePath,
    required _i2.ConversionRule? rule,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#previewImport, [], {
              #filePath: filePath,
              #rule: rule,
            }),
            returnValue: _i5.Future<List<_i6.Node>>.value(<_i6.Node>[]),
          )
          as _i5.Future<List<_i6.Node>>);

  @override
  _i5.Future<_i2.ConversionResult> executeImport({
    required String? filePath,
    required _i2.ConversionRule? rule,
    required List<int>? selectedIndices,
    bool? addToGraph = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#executeImport, [], {
              #filePath: filePath,
              #rule: rule,
              #selectedIndices: selectedIndices,
              #addToGraph: addToGraph,
            }),
            returnValue: _i5.Future<_i2.ConversionResult>.value(
              _FakeConversionResult_0(
                this,
                Invocation.method(#executeImport, [], {
                  #filePath: filePath,
                  #rule: rule,
                  #selectedIndices: selectedIndices,
                  #addToGraph: addToGraph,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.ConversionResult>);

  @override
  _i5.Future<String> previewExport({
    required List<String>? nodeIds,
    required _i2.MergeRule? rule,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#previewExport, [], {
              #nodeIds: nodeIds,
              #rule: rule,
            }),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#previewExport, [], {
                  #nodeIds: nodeIds,
                  #rule: rule,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i3.File> executeExport({
    required List<String>? nodeIds,
    required _i2.MergeRule? rule,
    required String? outputPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#executeExport, [], {
              #nodeIds: nodeIds,
              #rule: rule,
              #outputPath: outputPath,
            }),
            returnValue: _i5.Future<_i3.File>.value(
              _FakeFile_1(
                this,
                Invocation.method(#executeExport, [], {
                  #nodeIds: nodeIds,
                  #rule: rule,
                  #outputPath: outputPath,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.File>);

  @override
  _i5.Future<_i2.ConversionResult> batchImport({
    required List<String>? filePaths,
    required _i2.ConversionConfig? config,
    void Function(int, int)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#batchImport, [], {
              #filePaths: filePaths,
              #config: config,
              #onProgress: onProgress,
            }),
            returnValue: _i5.Future<_i2.ConversionResult>.value(
              _FakeConversionResult_0(
                this,
                Invocation.method(#batchImport, [], {
                  #filePaths: filePaths,
                  #config: config,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.ConversionResult>);
}
