// Mocks generated by Mockito 5.4.6 from annotations
// in node_graph_notebook/test/core/services/data_recovery_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i10;

import 'package:flutter/material.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:node_graph_notebook/core/models/models.dart' as _i2;
import 'package:node_graph_notebook/core/repositories/graph_repository.dart'
    as _i7;
import 'package:node_graph_notebook/core/repositories/node_repository.dart'
    as _i4;
import 'package:node_graph_notebook/core/services/infrastructure/storage_path_service.dart'
    as _i3;
import 'package:node_graph_notebook/core/services/settings_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMetadataIndex_0 extends _i1.SmartFake implements _i2.MetadataIndex {
  _FakeMetadataIndex_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGraph_1 extends _i1.SmartFake implements _i2.Graph {
  _FakeGraph_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStorageUsage_2 extends _i1.SmartFake implements _i3.StorageUsage {
  _FakeStorageUsage_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeRepository extends _i1.Mock implements _i4.NodeRepository {
  MockNodeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> save(_i2.Node? node) =>
      (super.noSuchMethod(
            Invocation.method(#save, [node]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Node?> load(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#load, [nodeId]),
            returnValue: _i5.Future<_i2.Node?>.value(),
          )
          as _i5.Future<_i2.Node?>);

  @override
  _i5.Future<void> delete(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [nodeId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveAll(List<_i2.Node>? nodes) =>
      (super.noSuchMethod(
            Invocation.method(#saveAll, [nodes]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Node>> loadAll(List<String>? nodeIds) =>
      (super.noSuchMethod(
            Invocation.method(#loadAll, [nodeIds]),
            returnValue: _i5.Future<List<_i2.Node>>.value(<_i2.Node>[]),
          )
          as _i5.Future<List<_i2.Node>>);

  @override
  _i5.Future<List<_i2.Node>> queryAll() =>
      (super.noSuchMethod(
            Invocation.method(#queryAll, []),
            returnValue: _i5.Future<List<_i2.Node>>.value(<_i2.Node>[]),
          )
          as _i5.Future<List<_i2.Node>>);

  @override
  _i5.Future<List<_i2.Node>> search({
    String? title,
    String? content,
    List<String>? tags,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [], {
              #title: title,
              #content: content,
              #tags: tags,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i5.Future<List<_i2.Node>>.value(<_i2.Node>[]),
          )
          as _i5.Future<List<_i2.Node>>);

  @override
  String getNodeFilePath(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getNodeFilePath, [nodeId]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getNodeFilePath, [nodeId]),
            ),
          )
          as String);

  @override
  _i5.Future<_i2.MetadataIndex> getMetadataIndex() =>
      (super.noSuchMethod(
            Invocation.method(#getMetadataIndex, []),
            returnValue: _i5.Future<_i2.MetadataIndex>.value(
              _FakeMetadataIndex_0(
                this,
                Invocation.method(#getMetadataIndex, []),
              ),
            ),
          )
          as _i5.Future<_i2.MetadataIndex>);

  @override
  _i5.Future<void> updateIndex(_i2.Node? node) =>
      (super.noSuchMethod(
            Invocation.method(#updateIndex, [node]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [GraphRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphRepository extends _i1.Mock implements _i7.GraphRepository {
  MockGraphRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> save(_i2.Graph? graph) =>
      (super.noSuchMethod(
            Invocation.method(#save, [graph]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Graph?> load(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#load, [graphId]),
            returnValue: _i5.Future<_i2.Graph?>.value(),
          )
          as _i5.Future<_i2.Graph?>);

  @override
  _i5.Future<void> delete(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [graphId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Graph>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i5.Future<List<_i2.Graph>>.value(<_i2.Graph>[]),
          )
          as _i5.Future<List<_i2.Graph>>);

  @override
  _i5.Future<_i2.Graph?> getCurrent() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrent, []),
            returnValue: _i5.Future<_i2.Graph?>.value(),
          )
          as _i5.Future<_i2.Graph?>);

  @override
  _i5.Future<void> setCurrent(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrent, [graphId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> export(String? graphId, String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#export, [graphId, filePath]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Graph> import(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#import, [filePath]),
            returnValue: _i5.Future<_i2.Graph>.value(
              _FakeGraph_1(this, Invocation.method(#import, [filePath])),
            ),
          )
          as _i5.Future<_i2.Graph>);
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i8.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.ThemeMode get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _i9.ThemeMode.system,
          )
          as _i9.ThemeMode);

  @override
  bool get isUsingDefaultPath =>
      (super.noSuchMethod(
            Invocation.getter(#isUsingDefaultPath),
            returnValue: false,
          )
          as bool);

  @override
  String get aiProvider =>
      (super.noSuchMethod(
            Invocation.getter(#aiProvider),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#aiProvider),
            ),
          )
          as String);

  @override
  String get aiBaseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#aiBaseUrl),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#aiBaseUrl),
            ),
          )
          as String);

  @override
  String get aiModel =>
      (super.noSuchMethod(
            Invocation.getter(#aiModel),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#aiModel),
            ),
          )
          as String);

  @override
  bool get isAIConfigured =>
      (super.noSuchMethod(
            Invocation.getter(#isAIConfigured),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> getStoragePath() =>
      (super.noSuchMethod(
            Invocation.method(#getStoragePath, []),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getStoragePath, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> getNodesPath() =>
      (super.noSuchMethod(
            Invocation.method(#getNodesPath, []),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getNodesPath, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> getGraphsPath() =>
      (super.noSuchMethod(
            Invocation.method(#getGraphsPath, []),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getGraphsPath, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> getSettingsPath() =>
      (super.noSuchMethod(
            Invocation.method(#getSettingsPath, []),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getSettingsPath, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> getPluginsPath() =>
      (super.noSuchMethod(
            Invocation.method(#getPluginsPath, []),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getPluginsPath, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<bool> setCustomStoragePath(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setCustomStoragePath, [path]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String?> selectStoragePath() =>
      (super.noSuchMethod(
            Invocation.method(#selectStoragePath, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> setThemeMode(_i9.ThemeMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setThemeMode, [mode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setDefaultViewMode(String? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultViewMode, [mode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> validateStoragePath(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#validateStoragePath, [path]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.StorageUsage> getStorageUsage() =>
      (super.noSuchMethod(
            Invocation.method(#getStorageUsage, []),
            returnValue: _i5.Future<_i3.StorageUsage>.value(
              _FakeStorageUsage_2(
                this,
                Invocation.method(#getStorageUsage, []),
              ),
            ),
          )
          as _i5.Future<_i3.StorageUsage>);

  @override
  _i5.Future<void> resetToDefaults() =>
      (super.noSuchMethod(
            Invocation.method(#resetToDefaults, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setAIProvider(String? provider) =>
      (super.noSuchMethod(
            Invocation.method(#setAIProvider, [provider]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setAIBaseUrl(String? baseUrl) =>
      (super.noSuchMethod(
            Invocation.method(#setAIBaseUrl, [baseUrl]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setAIModel(String? model) =>
      (super.noSuchMethod(
            Invocation.method(#setAIModel, [model]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setAIApiKey(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#setAIApiKey, [apiKey]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
