// Mocks generated by Mockito 5.4.6 from annotations
// in node_graph_notebook/test/plugins/search/handler/search_handlers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:node_graph_notebook/core/commands/command_bus.dart' as _i3;
import 'package:node_graph_notebook/core/commands/models/command_context.dart'
    as _i7;
import 'package:node_graph_notebook/core/events/app_events.dart' as _i9;
import 'package:node_graph_notebook/core/models/node.dart' as _i10;
import 'package:node_graph_notebook/core/repositories/graph_repository.dart'
    as _i5;
import 'package:node_graph_notebook/core/repositories/node_repository.dart'
    as _i4;
import 'package:node_graph_notebook/plugins/search/model/search_preset_model.dart'
    as _i2;
import 'package:node_graph_notebook/plugins/search/service/search_preset_service.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSearchPreset_0 extends _i1.SmartFake implements _i2.SearchPreset {
  _FakeSearchPreset_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommandBus_1 extends _i1.SmartFake implements _i3.CommandBus {
  _FakeCommandBus_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNodeRepository_2 extends _i1.SmartFake
    implements _i4.NodeRepository {
  _FakeNodeRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGraphRepository_3 extends _i1.SmartFake
    implements _i5.GraphRepository {
  _FakeGraphRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_4<T1> extends _i1.SmartFake implements _i6.Future<T1> {
  _FakeFuture_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommandContext_5 extends _i1.SmartFake
    implements _i7.CommandContext {
  _FakeCommandContext_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchPresetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchPresetService extends _i1.Mock
    implements _i8.SearchPresetService {
  MockSearchPresetService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.SearchPreset>> getAllPresets() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPresets, []),
            returnValue: _i6.Future<List<_i2.SearchPreset>>.value(
              <_i2.SearchPreset>[],
            ),
          )
          as _i6.Future<List<_i2.SearchPreset>>);

  @override
  _i6.Future<_i2.SearchPreset?> getPreset(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPreset, [id]),
            returnValue: _i6.Future<_i2.SearchPreset?>.value(),
          )
          as _i6.Future<_i2.SearchPreset?>);

  @override
  _i6.Future<_i2.SearchPreset> savePreset(_i2.SearchPreset? preset) =>
      (super.noSuchMethod(
            Invocation.method(#savePreset, [preset]),
            returnValue: _i6.Future<_i2.SearchPreset>.value(
              _FakeSearchPreset_0(
                this,
                Invocation.method(#savePreset, [preset]),
              ),
            ),
          )
          as _i6.Future<_i2.SearchPreset>);

  @override
  _i6.Future<void> deletePreset(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePreset, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateLastUsed(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastUsed, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [CommandContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommandContext extends _i1.Mock implements _i7.CommandContext {
  MockCommandContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CommandBus get commandBus =>
      (super.noSuchMethod(
            Invocation.getter(#commandBus),
            returnValue: _FakeCommandBus_1(
              this,
              Invocation.getter(#commandBus),
            ),
          )
          as _i3.CommandBus);

  @override
  _i4.NodeRepository get nodeRepository =>
      (super.noSuchMethod(
            Invocation.getter(#nodeRepository),
            returnValue: _FakeNodeRepository_2(
              this,
              Invocation.getter(#nodeRepository),
            ),
          )
          as _i4.NodeRepository);

  @override
  _i5.GraphRepository get graphRepository =>
      (super.noSuchMethod(
            Invocation.getter(#graphRepository),
            returnValue: _FakeGraphRepository_3(
              this,
              Invocation.getter(#graphRepository),
            ),
          )
          as _i5.GraphRepository);

  @override
  bool get isInTransaction =>
      (super.noSuchMethod(
            Invocation.getter(#isInTransaction),
            returnValue: false,
          )
          as bool);

  @override
  set commandBus(_i3.CommandBus? value) => super.noSuchMethod(
    Invocation.setter(#commandBus, value),
    returnValueForMissingStub: null,
  );

  @override
  void publishEvent(_i9.AppEvent? event) => super.noSuchMethod(
    Invocation.method(#publishEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void publishEvents(List<_i9.AppEvent>? events) => super.noSuchMethod(
    Invocation.method(#publishEvents, [events]),
    returnValueForMissingStub: null,
  );

  @override
  List<_i9.AppEvent> getPendingEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingEvents, []),
            returnValue: <_i9.AppEvent>[],
          )
          as List<_i9.AppEvent>);

  @override
  void clearPendingEvents() => super.noSuchMethod(
    Invocation.method(#clearPendingEvents, []),
    returnValueForMissingStub: null,
  );

  @override
  void publishNodeEvent(List<_i10.Node>? nodes, _i9.DataChangeAction? action) =>
      super.noSuchMethod(
        Invocation.method(#publishNodeEvent, [nodes, action]),
        returnValueForMissingStub: null,
      );

  @override
  void publishSingleNodeEvent(_i10.Node? node, _i9.DataChangeAction? action) =>
      super.noSuchMethod(
        Invocation.method(#publishSingleNodeEvent, [node, action]),
        returnValueForMissingStub: null,
      );

  @override
  void publishGraphRelationEvent(
    String? graphId,
    List<String>? nodeIds,
    _i9.RelationChangeAction? action,
  ) => super.noSuchMethod(
    Invocation.method(#publishGraphRelationEvent, [graphId, nodeIds, action]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<T> withTransaction<T>(_i6.Future<T> Function()? operation) =>
      (super.noSuchMethod(
            Invocation.method(#withTransaction, [operation]),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#withTransaction, [operation]),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_4<T>(
                  this,
                  Invocation.method(#withTransaction, [operation]),
                ),
          )
          as _i6.Future<T>);

  @override
  void registerService<T>(T? service) => super.noSuchMethod(
    Invocation.method(#registerService, [service]),
    returnValueForMissingStub: null,
  );

  @override
  T read<T>() =>
      (super.noSuchMethod(
            Invocation.method(#read, []),
            returnValue: _i11.dummyValue<T>(this, Invocation.method(#read, [])),
          )
          as T);

  @override
  void setMetadata(String? key, dynamic value) => super.noSuchMethod(
    Invocation.method(#setMetadata, [key, value]),
    returnValueForMissingStub: null,
  );

  @override
  dynamic getMetadata(String? key) =>
      super.noSuchMethod(Invocation.method(#getMetadata, [key]));

  @override
  bool hasMetadata(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#hasMetadata, [key]),
            returnValue: false,
          )
          as bool);

  @override
  void clearMetadata() => super.noSuchMethod(
    Invocation.method(#clearMetadata, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.CommandContext createChild() =>
      (super.noSuchMethod(
            Invocation.method(#createChild, []),
            returnValue: _FakeCommandContext_5(
              this,
              Invocation.method(#createChild, []),
            ),
          )
          as _i7.CommandContext);
}
