name: node_settings
version: 1.0.0
description: The core package for node data structures and utilities.
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  
  # File System
  path_provider: ^2.1.1
  path: ^1.8.3

  core:
    path: ../core
  
  appframe:
    path: ../appframe

  provider: any
  flutter_bloc: any
  plugin: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

  # Testing
  mockito: ^5.4.2
  bloc_test: ^10.0.0
  integration_test:
    sdk: flutter
  test: ^1.30.0

  # Development Tools
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
