// Mocks generated by Mockito 5.4.6 from annotations
// in node_graph_notebook/test/plugins/graph/bloc/graph_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:node_graph_notebook/core/commands/command_bus.dart' as _i4;
import 'package:node_graph_notebook/core/commands/models/command.dart' as _i2;
import 'package:node_graph_notebook/core/commands/models/command_handler.dart'
    as _i6;
import 'package:node_graph_notebook/core/commands/models/middleware.dart'
    as _i7;
import 'package:node_graph_notebook/core/events/app_events.dart' as _i12;
import 'package:node_graph_notebook/core/models/models.dart' as _i3;
import 'package:node_graph_notebook/core/plugin/middleware/middleware_plugin.dart'
    as _i8;
import 'package:node_graph_notebook/core/repositories/graph_repository.dart'
    as _i9;
import 'package:node_graph_notebook/core/repositories/node_repository.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCommandResult_0<T1> extends _i1.SmartFake
    implements _i2.CommandResult<T1> {
  _FakeCommandResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGraph_1 extends _i1.SmartFake implements _i3.Graph {
  _FakeGraph_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMetadataIndex_2 extends _i1.SmartFake implements _i3.MetadataIndex {
  _FakeMetadataIndex_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CommandBus].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommandBus extends _i1.Mock implements _i4.CommandBus {
  MockCommandBus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i4.CommandEvent> get commandStream =>
      (super.noSuchMethod(
            Invocation.getter(#commandStream),
            returnValue: _i5.Stream<_i4.CommandEvent>.empty(),
          )
          as _i5.Stream<_i4.CommandEvent>);

  @override
  void registerHandler<T extends _i2.Command<dynamic>>(
    _i6.CommandHandler<T>? handler,
    Type? commandType,
  ) => super.noSuchMethod(
    Invocation.method(#registerHandler, [handler, commandType]),
    returnValueForMissingStub: null,
  );

  @override
  void registerHandlers(
    Map<Type, _i6.CommandHandler<_i2.Command<dynamic>>>? handlers,
  ) => super.noSuchMethod(
    Invocation.method(#registerHandlers, [handlers]),
    returnValueForMissingStub: null,
  );

  @override
  void addMiddleware(_i7.CommandMiddleware? middleware) => super.noSuchMethod(
    Invocation.method(#addMiddleware, [middleware]),
    returnValueForMissingStub: null,
  );

  @override
  void addMiddlewarePlugin(_i8.CommandMiddlewarePlugin? middleware) =>
      super.noSuchMethod(
        Invocation.method(#addMiddlewarePlugin, [middleware]),
        returnValueForMissingStub: null,
      );

  @override
  void removeMiddlewarePlugin(_i8.CommandMiddlewarePlugin? middleware) =>
      super.noSuchMethod(
        Invocation.method(#removeMiddlewarePlugin, [middleware]),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i2.CommandResult<T>> dispatch<T>(_i2.Command<T>? command) =>
      (super.noSuchMethod(
            Invocation.method(#dispatch, [command]),
            returnValue: _i5.Future<_i2.CommandResult<T>>.value(
              _FakeCommandResult_0<T>(
                this,
                Invocation.method(#dispatch, [command]),
              ),
            ),
          )
          as _i5.Future<_i2.CommandResult<T>>);

  @override
  _i5.Future<void> undo(_i2.Command<dynamic>? command) =>
      (super.noSuchMethod(
            Invocation.method(#undo, [command]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GraphRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphRepository extends _i1.Mock implements _i9.GraphRepository {
  MockGraphRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> save(_i3.Graph? graph) =>
      (super.noSuchMethod(
            Invocation.method(#save, [graph]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.Graph?> load(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#load, [graphId]),
            returnValue: _i5.Future<_i3.Graph?>.value(),
          )
          as _i5.Future<_i3.Graph?>);

  @override
  _i5.Future<void> delete(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [graphId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Graph>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i5.Future<List<_i3.Graph>>.value(<_i3.Graph>[]),
          )
          as _i5.Future<List<_i3.Graph>>);

  @override
  _i5.Future<_i3.Graph?> getCurrent() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrent, []),
            returnValue: _i5.Future<_i3.Graph?>.value(),
          )
          as _i5.Future<_i3.Graph?>);

  @override
  _i5.Future<void> setCurrent(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrent, [graphId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> export(String? graphId, String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#export, [graphId, filePath]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.Graph> import(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#import, [filePath]),
            returnValue: _i5.Future<_i3.Graph>.value(
              _FakeGraph_1(this, Invocation.method(#import, [filePath])),
            ),
          )
          as _i5.Future<_i3.Graph>);
}

/// A class which mocks [NodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeRepository extends _i1.Mock implements _i10.NodeRepository {
  MockNodeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> save(_i3.Node? node) =>
      (super.noSuchMethod(
            Invocation.method(#save, [node]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.Node?> load(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#load, [nodeId]),
            returnValue: _i5.Future<_i3.Node?>.value(),
          )
          as _i5.Future<_i3.Node?>);

  @override
  _i5.Future<void> delete(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [nodeId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveAll(List<_i3.Node>? nodes) =>
      (super.noSuchMethod(
            Invocation.method(#saveAll, [nodes]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Node>> loadAll(List<String>? nodeIds) =>
      (super.noSuchMethod(
            Invocation.method(#loadAll, [nodeIds]),
            returnValue: _i5.Future<List<_i3.Node>>.value(<_i3.Node>[]),
          )
          as _i5.Future<List<_i3.Node>>);

  @override
  _i5.Future<List<_i3.Node>> queryAll() =>
      (super.noSuchMethod(
            Invocation.method(#queryAll, []),
            returnValue: _i5.Future<List<_i3.Node>>.value(<_i3.Node>[]),
          )
          as _i5.Future<List<_i3.Node>>);

  @override
  _i5.Future<List<_i3.Node>> search({
    String? title,
    String? content,
    List<String>? tags,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [], {
              #title: title,
              #content: content,
              #tags: tags,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i5.Future<List<_i3.Node>>.value(<_i3.Node>[]),
          )
          as _i5.Future<List<_i3.Node>>);

  @override
  String getNodeFilePath(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getNodeFilePath, [nodeId]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#getNodeFilePath, [nodeId]),
            ),
          )
          as String);

  @override
  _i5.Future<_i3.MetadataIndex> getMetadataIndex() =>
      (super.noSuchMethod(
            Invocation.method(#getMetadataIndex, []),
            returnValue: _i5.Future<_i3.MetadataIndex>.value(
              _FakeMetadataIndex_2(
                this,
                Invocation.method(#getMetadataIndex, []),
              ),
            ),
          )
          as _i5.Future<_i3.MetadataIndex>);

  @override
  _i5.Future<void> updateIndex(_i3.Node? node) =>
      (super.noSuchMethod(
            Invocation.method(#updateIndex, [node]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [AppEventBus].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppEventBus extends _i1.Mock implements _i12.AppEventBus {
  MockAppEventBus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i12.AppEvent> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i12.AppEvent>.empty(),
          )
          as _i5.Stream<_i12.AppEvent>);

  @override
  set onError(void Function(_i12.AppEvent?, Object, StackTrace)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onError, value),
        returnValueForMissingStub: null,
      );

  @override
  void publish(_i12.AppEvent? event) => super.noSuchMethod(
    Invocation.method(#publish, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
