name: node_folder
version: 1.0.0
description: Folder management plugin for Node Graph Notebook.
publish_to: none
environment:
  sdk: '>=3.8.0 <4.0.0'
resolution: workspace
dependencies:
  core_data:
    path: ../core_data
  plugin:
    path: ../plugin
  flutter: { sdk: flutter }
  flutter_bloc: ^9.1.1
  provider: ^6.1.1
  core: { path: ../core }
  appframe: { path: ../appframe }
  node_graph: any
  node_editor: any
dev_dependencies:
  flutter_test: { sdk: flutter }
