// Mocks generated by Mockito 5.4.6 from annotations
// in node_graph_notebook/test/plugins/lua/integration/lua_deep_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:node_graph_notebook/core/models/models.dart' as _i2;
import 'package:node_graph_notebook/core/repositories/graph_repository.dart'
    as _i6;
import 'package:node_graph_notebook/core/repositories/node_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMetadataIndex_0 extends _i1.SmartFake implements _i2.MetadataIndex {
  _FakeMetadataIndex_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGraph_1 extends _i1.SmartFake implements _i2.Graph {
  _FakeGraph_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeRepository extends _i1.Mock implements _i3.NodeRepository {
  MockNodeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> save(_i2.Node? node) =>
      (super.noSuchMethod(
            Invocation.method(#save, [node]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Node?> load(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#load, [nodeId]),
            returnValue: _i4.Future<_i2.Node?>.value(),
          )
          as _i4.Future<_i2.Node?>);

  @override
  _i4.Future<void> delete(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [nodeId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveAll(List<_i2.Node>? nodes) =>
      (super.noSuchMethod(
            Invocation.method(#saveAll, [nodes]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Node>> loadAll(List<String>? nodeIds) =>
      (super.noSuchMethod(
            Invocation.method(#loadAll, [nodeIds]),
            returnValue: _i4.Future<List<_i2.Node>>.value(<_i2.Node>[]),
          )
          as _i4.Future<List<_i2.Node>>);

  @override
  _i4.Future<List<_i2.Node>> queryAll() =>
      (super.noSuchMethod(
            Invocation.method(#queryAll, []),
            returnValue: _i4.Future<List<_i2.Node>>.value(<_i2.Node>[]),
          )
          as _i4.Future<List<_i2.Node>>);

  @override
  _i4.Future<List<_i2.Node>> search({
    String? title,
    String? content,
    List<String>? tags,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [], {
              #title: title,
              #content: content,
              #tags: tags,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i4.Future<List<_i2.Node>>.value(<_i2.Node>[]),
          )
          as _i4.Future<List<_i2.Node>>);

  @override
  String getNodeFilePath(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getNodeFilePath, [nodeId]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getNodeFilePath, [nodeId]),
            ),
          )
          as String);

  @override
  _i4.Future<_i2.MetadataIndex> getMetadataIndex() =>
      (super.noSuchMethod(
            Invocation.method(#getMetadataIndex, []),
            returnValue: _i4.Future<_i2.MetadataIndex>.value(
              _FakeMetadataIndex_0(
                this,
                Invocation.method(#getMetadataIndex, []),
              ),
            ),
          )
          as _i4.Future<_i2.MetadataIndex>);

  @override
  _i4.Future<void> updateIndex(_i2.Node? node) =>
      (super.noSuchMethod(
            Invocation.method(#updateIndex, [node]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [GraphRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphRepository extends _i1.Mock implements _i6.GraphRepository {
  MockGraphRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> save(_i2.Graph? graph) =>
      (super.noSuchMethod(
            Invocation.method(#save, [graph]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Graph?> load(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#load, [graphId]),
            returnValue: _i4.Future<_i2.Graph?>.value(),
          )
          as _i4.Future<_i2.Graph?>);

  @override
  _i4.Future<void> delete(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [graphId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Graph>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i4.Future<List<_i2.Graph>>.value(<_i2.Graph>[]),
          )
          as _i4.Future<List<_i2.Graph>>);

  @override
  _i4.Future<_i2.Graph?> getCurrent() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrent, []),
            returnValue: _i4.Future<_i2.Graph?>.value(),
          )
          as _i4.Future<_i2.Graph?>);

  @override
  _i4.Future<void> setCurrent(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrent, [graphId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> export(String? graphId, String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#export, [graphId, filePath]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Graph> import(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#import, [filePath]),
            returnValue: _i4.Future<_i2.Graph>.value(
              _FakeGraph_1(this, Invocation.method(#import, [filePath])),
            ),
          )
          as _i4.Future<_i2.Graph>);
}
