name: repository_fs
version: 0.1.0
description: Filesystem-based repository implementations for Node Graph Notebook.
publish_to: none
environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  path: ^1.8.3
  uuid: ^4.2.1

  core_data: any
dev_dependencies:
  flutter_test:
    sdk: flutter
