// Mocks generated by Mockito 5.4.6 from annotations
// in node_graph_notebook/test/plugins/search/bloc/search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:node_graph_notebook/core/commands/command_bus.dart' as _i11;
import 'package:node_graph_notebook/core/commands/models/command.dart' as _i4;
import 'package:node_graph_notebook/core/commands/models/command_handler.dart'
    as _i13;
import 'package:node_graph_notebook/core/commands/models/middleware.dart'
    as _i14;
import 'package:node_graph_notebook/core/cqrs/query/query.dart' as _i6;
import 'package:node_graph_notebook/core/cqrs/query/query_bus.dart' as _i16;
import 'package:node_graph_notebook/core/cqrs/query/query_cache.dart' as _i5;
import 'package:node_graph_notebook/core/events/app_events.dart' as _i12;
import 'package:node_graph_notebook/core/models/models.dart' as _i2;
import 'package:node_graph_notebook/core/plugin/middleware/middleware_plugin.dart'
    as _i15;
import 'package:node_graph_notebook/plugins/graph/service/node_service.dart'
    as _i7;
import 'package:node_graph_notebook/plugins/search/model/search_preset_model.dart'
    as _i3;
import 'package:node_graph_notebook/plugins/search/service/search_preset_service.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNode_0 extends _i1.SmartFake implements _i2.Node {
  _FakeNode_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchPreset_1 extends _i1.SmartFake implements _i3.SearchPreset {
  _FakeSearchPreset_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommandResult_2<T1> extends _i1.SmartFake
    implements _i4.CommandResult<T1> {
  _FakeCommandResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryCacheStats_3 extends _i1.SmartFake
    implements _i5.QueryCacheStats {
  _FakeQueryCacheStats_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryResult_4<T1> extends _i1.SmartFake
    implements _i6.QueryResult<T1> {
  _FakeQueryResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NodeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeService extends _i1.Mock implements _i7.NodeService {
  MockNodeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Node> createNode({
    required String? title,
    String? content,
    _i9.Offset? position,
    _i9.Size? size,
    String? color,
    Map<String, _i2.NodeReference>? references,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createNode, [], {
              #title: title,
              #content: content,
              #position: position,
              #size: size,
              #color: color,
              #references: references,
              #metadata: metadata,
            }),
            returnValue: _i8.Future<_i2.Node>.value(
              _FakeNode_0(
                this,
                Invocation.method(#createNode, [], {
                  #title: title,
                  #content: content,
                  #position: position,
                  #size: size,
                  #color: color,
                  #references: references,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.Node>);

  @override
  _i8.Future<_i2.Node> updateNode(
    String? nodeId, {
    String? title,
    String? content,
    _i9.Offset? position,
    _i9.Size? size,
    _i2.NodeViewMode? viewMode,
    String? color,
    Map<String, _i2.NodeReference>? references,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateNode,
              [nodeId],
              {
                #title: title,
                #content: content,
                #position: position,
                #size: size,
                #viewMode: viewMode,
                #color: color,
                #references: references,
                #metadata: metadata,
              },
            ),
            returnValue: _i8.Future<_i2.Node>.value(
              _FakeNode_0(
                this,
                Invocation.method(
                  #updateNode,
                  [nodeId],
                  {
                    #title: title,
                    #content: content,
                    #position: position,
                    #size: size,
                    #viewMode: viewMode,
                    #color: color,
                    #references: references,
                    #metadata: metadata,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<_i2.Node>);

  @override
  _i8.Future<void> deleteNode(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNode, [nodeId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i2.Node?> getNode(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getNode, [nodeId]),
            returnValue: _i8.Future<_i2.Node?>.value(),
          )
          as _i8.Future<_i2.Node?>);

  @override
  _i8.Future<List<_i2.Node>> getAllNodes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNodes, []),
            returnValue: _i8.Future<List<_i2.Node>>.value(<_i2.Node>[]),
          )
          as _i8.Future<List<_i2.Node>>);

  @override
  _i8.Future<List<_i2.Node>> searchNodes(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchNodes, [query]),
            returnValue: _i8.Future<List<_i2.Node>>.value(<_i2.Node>[]),
          )
          as _i8.Future<List<_i2.Node>>);

  @override
  _i8.Future<void> connectNodes({
    required String? fromNodeId,
    required String? toNodeId,
    Map<String, dynamic>? properties,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#connectNodes, [], {
              #fromNodeId: fromNodeId,
              #toNodeId: toNodeId,
              #properties: properties,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> disconnectNodes({
    required String? fromNodeId,
    required String? toNodeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectNodes, [], {
              #fromNodeId: fromNodeId,
              #toNodeId: toNodeId,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> batchUpdate(List<_i7.NodeUpdate>? updates) =>
      (super.noSuchMethod(
            Invocation.method(#batchUpdate, [updates]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> batchDelete(List<String>? nodeIds) =>
      (super.noSuchMethod(
            Invocation.method(#batchDelete, [nodeIds]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, int>> calculateNodeDepths(List<_i2.Node>? nodes) =>
      (super.noSuchMethod(
            Invocation.method(#calculateNodeDepths, [nodes]),
            returnValue: _i8.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i8.Future<Map<String, int>>);
}

/// A class which mocks [SearchPresetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchPresetService extends _i1.Mock
    implements _i10.SearchPresetService {
  MockSearchPresetService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i3.SearchPreset>> getAllPresets() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPresets, []),
            returnValue: _i8.Future<List<_i3.SearchPreset>>.value(
              <_i3.SearchPreset>[],
            ),
          )
          as _i8.Future<List<_i3.SearchPreset>>);

  @override
  _i8.Future<_i3.SearchPreset?> getPreset(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPreset, [id]),
            returnValue: _i8.Future<_i3.SearchPreset?>.value(),
          )
          as _i8.Future<_i3.SearchPreset?>);

  @override
  _i8.Future<_i3.SearchPreset> savePreset(_i3.SearchPreset? preset) =>
      (super.noSuchMethod(
            Invocation.method(#savePreset, [preset]),
            returnValue: _i8.Future<_i3.SearchPreset>.value(
              _FakeSearchPreset_1(
                this,
                Invocation.method(#savePreset, [preset]),
              ),
            ),
          )
          as _i8.Future<_i3.SearchPreset>);

  @override
  _i8.Future<void> deletePreset(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePreset, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateLastUsed(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastUsed, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [CommandBus].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommandBus extends _i1.Mock implements _i11.CommandBus {
  MockCommandBus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<_i11.CommandEvent> get commandStream =>
      (super.noSuchMethod(
            Invocation.getter(#commandStream),
            returnValue: _i8.Stream<_i11.CommandEvent>.empty(),
          )
          as _i8.Stream<_i11.CommandEvent>);

  @override
  _i8.Stream<_i12.AppEvent> get eventStream =>
      (super.noSuchMethod(
            Invocation.getter(#eventStream),
            returnValue: _i8.Stream<_i12.AppEvent>.empty(),
          )
          as _i8.Stream<_i12.AppEvent>);

  @override
  void registerHandler<T extends _i4.Command<dynamic>>(
    _i13.CommandHandler<T>? handler,
    Type? commandType,
  ) => super.noSuchMethod(
    Invocation.method(#registerHandler, [handler, commandType]),
    returnValueForMissingStub: null,
  );

  @override
  void registerHandlers(
    Map<Type, _i13.CommandHandler<_i4.Command<dynamic>>>? handlers,
  ) => super.noSuchMethod(
    Invocation.method(#registerHandlers, [handlers]),
    returnValueForMissingStub: null,
  );

  @override
  void addMiddleware(_i14.CommandMiddleware? middleware) => super.noSuchMethod(
    Invocation.method(#addMiddleware, [middleware]),
    returnValueForMissingStub: null,
  );

  @override
  void addMiddlewarePlugin(_i15.CommandMiddlewarePlugin? middleware) =>
      super.noSuchMethod(
        Invocation.method(#addMiddlewarePlugin, [middleware]),
        returnValueForMissingStub: null,
      );

  @override
  void removeMiddlewarePlugin(_i15.CommandMiddlewarePlugin? middleware) =>
      super.noSuchMethod(
        Invocation.method(#removeMiddlewarePlugin, [middleware]),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i4.CommandResult<T>> dispatch<T>(_i4.Command<T>? command) =>
      (super.noSuchMethod(
            Invocation.method(#dispatch, [command]),
            returnValue: _i8.Future<_i4.CommandResult<T>>.value(
              _FakeCommandResult_2<T>(
                this,
                Invocation.method(#dispatch, [command]),
              ),
            ),
          )
          as _i8.Future<_i4.CommandResult<T>>);

  @override
  _i8.Future<void> undo(_i4.Command<dynamic>? command) =>
      (super.noSuchMethod(
            Invocation.method(#undo, [command]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void publishEvent(_i12.AppEvent? event) => super.noSuchMethod(
    Invocation.method(#publishEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void publishEvents(List<_i12.AppEvent>? events) => super.noSuchMethod(
    Invocation.method(#publishEvents, [events]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [QueryBus].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueryBus extends _i1.Mock implements _i16.QueryBus {
  MockQueryBus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.QueryCacheStats get cacheStats =>
      (super.noSuchMethod(
            Invocation.getter(#cacheStats),
            returnValue: _FakeQueryCacheStats_3(
              this,
              Invocation.getter(#cacheStats),
            ),
          )
          as _i5.QueryCacheStats);

  @override
  void registerHandler<T, Q extends _i6.Query<T>>(
    Type? queryType,
    _i6.QueryHandler<T, Q> Function()? handlerFactory,
  ) => super.noSuchMethod(
    Invocation.method(#registerHandler, [queryType, handlerFactory]),
    returnValueForMissingStub: null,
  );

  @override
  void registerMiddleware(_i16.QueryMiddleware? middleware) =>
      super.noSuchMethod(
        Invocation.method(#registerMiddleware, [middleware]),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i6.QueryResult<T>> dispatch<T, Q extends _i6.Query<T>>(
    Q? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#dispatch, [query]),
            returnValue: _i8.Future<_i6.QueryResult<T>>.value(
              _FakeQueryResult_4<T>(
                this,
                Invocation.method(#dispatch, [query]),
              ),
            ),
          )
          as _i8.Future<_i6.QueryResult<T>>);

  @override
  void clearCache([Type? queryType]) => super.noSuchMethod(
    Invocation.method(#clearCache, [queryType]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
