// Mocks generated by Mockito 5.4.6 from annotations
// in node_graph_notebook/test/bloc/node/node_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:node_graph_notebook/core/models/models.dart' as _i2;
import 'package:node_graph_notebook/core/services/node_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNode_0 extends _i1.SmartFake implements _i2.Node {
  _FakeNode_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NodeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeService extends _i1.Mock implements _i3.NodeService {
  @override
  _i4.Future<_i2.Node> createNode({
    required String? title,
    String? content,
    _i5.Offset? position,
    _i5.Size? size,
    String? color,
    Map<String, _i2.NodeReference>? references,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createNode, [], {
              #title: title,
              #content: content,
              #position: position,
              #size: size,
              #color: color,
              #references: references,
              #metadata: metadata,
            }),
            returnValue: _i4.Future<_i2.Node>.value(
              _FakeNode_0(
                this,
                Invocation.method(#createNode, [], {
                  #title: title,
                  #content: content,
                  #position: position,
                  #size: size,
                  #color: color,
                  #references: references,
                  #metadata: metadata,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Node>.value(
              _FakeNode_0(
                this,
                Invocation.method(#createNode, [], {
                  #title: title,
                  #content: content,
                  #position: position,
                  #size: size,
                  #color: color,
                  #references: references,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Node>);

  @override
  _i4.Future<_i2.Node> updateNode(
    String? nodeId, {
    String? title,
    String? content,
    _i5.Offset? position,
    _i5.Size? size,
    _i2.NodeViewMode? viewMode,
    String? color,
    Map<String, _i2.NodeReference>? references,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateNode,
              [nodeId],
              {
                #title: title,
                #content: content,
                #position: position,
                #size: size,
                #viewMode: viewMode,
                #color: color,
                #references: references,
                #metadata: metadata,
              },
            ),
            returnValue: _i4.Future<_i2.Node>.value(
              _FakeNode_0(
                this,
                Invocation.method(
                  #updateNode,
                  [nodeId],
                  {
                    #title: title,
                    #content: content,
                    #position: position,
                    #size: size,
                    #viewMode: viewMode,
                    #color: color,
                    #references: references,
                    #metadata: metadata,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Node>.value(
              _FakeNode_0(
                this,
                Invocation.method(
                  #updateNode,
                  [nodeId],
                  {
                    #title: title,
                    #content: content,
                    #position: position,
                    #size: size,
                    #viewMode: viewMode,
                    #color: color,
                    #references: references,
                    #metadata: metadata,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Node>);

  @override
  _i4.Future<void> deleteNode(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNode, [nodeId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Node?> getNode(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getNode, [nodeId]),
            returnValue: _i4.Future<_i2.Node?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Node?>.value(),
          )
          as _i4.Future<_i2.Node?>);

  @override
  _i4.Future<List<_i2.Node>> getAllNodes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNodes, []),
            returnValue: _i4.Future<List<_i2.Node>>.value(<_i2.Node>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Node>>.value(
              <_i2.Node>[],
            ),
          )
          as _i4.Future<List<_i2.Node>>);

  @override
  _i4.Future<List<_i2.Node>> searchNodes(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchNodes, [query]),
            returnValue: _i4.Future<List<_i2.Node>>.value(<_i2.Node>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Node>>.value(
              <_i2.Node>[],
            ),
          )
          as _i4.Future<List<_i2.Node>>);

  @override
  _i4.Future<void> connectNodes({
    required String? fromNodeId,
    required String? toNodeId,
    required _i2.ReferenceType? type,
    String? role,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#connectNodes, [], {
              #fromNodeId: fromNodeId,
              #toNodeId: toNodeId,
              #type: type,
              #role: role,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disconnectNodes({
    required String? fromNodeId,
    required String? toNodeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectNodes, [], {
              #fromNodeId: fromNodeId,
              #toNodeId: toNodeId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> batchUpdate(List<_i3.NodeUpdate>? updates) =>
      (super.noSuchMethod(
            Invocation.method(#batchUpdate, [updates]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> batchDelete(List<String>? nodeIds) =>
      (super.noSuchMethod(
            Invocation.method(#batchDelete, [nodeIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
