// Mocks generated by Mockito 5.4.6 from annotations
// in node_graph_notebook/test/ui/cross_bloc_ui_update_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:node_graph_notebook/core/models/models.dart' as _i2;
import 'package:node_graph_notebook/core/repositories/repositories.dart' as _i3;
import 'package:node_graph_notebook/core/services/graph_service.dart' as _i8;
import 'package:node_graph_notebook/core/services/node_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMetadataIndex_0 extends _i1.SmartFake implements _i2.MetadataIndex {
  _FakeMetadataIndex_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGraph_1 extends _i1.SmartFake implements _i2.Graph {
  _FakeGraph_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNode_2 extends _i1.SmartFake implements _i2.Node {
  _FakeNode_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeRepository extends _i1.Mock implements _i3.NodeRepository {
  @override
  _i4.Future<void> save(_i2.Node? node) =>
      (super.noSuchMethod(
            Invocation.method(#save, [node]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Node?> load(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#load, [nodeId]),
            returnValue: _i4.Future<_i2.Node?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Node?>.value(),
          )
          as _i4.Future<_i2.Node?>);

  @override
  _i4.Future<void> delete(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [nodeId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveAll(List<_i2.Node>? nodes) =>
      (super.noSuchMethod(
            Invocation.method(#saveAll, [nodes]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Node>> loadAll(List<String>? nodeIds) =>
      (super.noSuchMethod(
            Invocation.method(#loadAll, [nodeIds]),
            returnValue: _i4.Future<List<_i2.Node>>.value(<_i2.Node>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Node>>.value(
              <_i2.Node>[],
            ),
          )
          as _i4.Future<List<_i2.Node>>);

  @override
  _i4.Future<List<_i2.Node>> queryAll() =>
      (super.noSuchMethod(
            Invocation.method(#queryAll, []),
            returnValue: _i4.Future<List<_i2.Node>>.value(<_i2.Node>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Node>>.value(
              <_i2.Node>[],
            ),
          )
          as _i4.Future<List<_i2.Node>>);

  @override
  _i4.Future<List<_i2.Node>> search({
    String? title,
    String? content,
    List<String>? tags,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [], {
              #title: title,
              #content: content,
              #tags: tags,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i4.Future<List<_i2.Node>>.value(<_i2.Node>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Node>>.value(
              <_i2.Node>[],
            ),
          )
          as _i4.Future<List<_i2.Node>>);

  @override
  String getNodeFilePath(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getNodeFilePath, [nodeId]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getNodeFilePath, [nodeId]),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.method(#getNodeFilePath, [nodeId]),
            ),
          )
          as String);

  @override
  _i4.Future<_i2.MetadataIndex> getMetadataIndex() =>
      (super.noSuchMethod(
            Invocation.method(#getMetadataIndex, []),
            returnValue: _i4.Future<_i2.MetadataIndex>.value(
              _FakeMetadataIndex_0(
                this,
                Invocation.method(#getMetadataIndex, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.MetadataIndex>.value(
              _FakeMetadataIndex_0(
                this,
                Invocation.method(#getMetadataIndex, []),
              ),
            ),
          )
          as _i4.Future<_i2.MetadataIndex>);

  @override
  _i4.Future<void> updateIndex(_i2.Node? node) =>
      (super.noSuchMethod(
            Invocation.method(#updateIndex, [node]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [GraphRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphRepository extends _i1.Mock implements _i3.GraphRepository {
  @override
  _i4.Future<void> save(_i2.Graph? graph) =>
      (super.noSuchMethod(
            Invocation.method(#save, [graph]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Graph?> load(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#load, [graphId]),
            returnValue: _i4.Future<_i2.Graph?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Graph?>.value(),
          )
          as _i4.Future<_i2.Graph?>);

  @override
  _i4.Future<void> delete(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [graphId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Graph>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i4.Future<List<_i2.Graph>>.value(<_i2.Graph>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Graph>>.value(
              <_i2.Graph>[],
            ),
          )
          as _i4.Future<List<_i2.Graph>>);

  @override
  _i4.Future<_i2.Graph?> getCurrent() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrent, []),
            returnValue: _i4.Future<_i2.Graph?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Graph?>.value(),
          )
          as _i4.Future<_i2.Graph?>);

  @override
  _i4.Future<void> setCurrent(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrent, [graphId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> export(String? graphId, String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#export, [graphId, filePath]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Graph> import(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#import, [filePath]),
            returnValue: _i4.Future<_i2.Graph>.value(
              _FakeGraph_1(this, Invocation.method(#import, [filePath])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Graph>.value(
              _FakeGraph_1(this, Invocation.method(#import, [filePath])),
            ),
          )
          as _i4.Future<_i2.Graph>);
}

/// A class which mocks [NodeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeService extends _i1.Mock implements _i6.NodeService {
  @override
  _i4.Future<_i2.Node> createNode({
    required String? title,
    String? content,
    _i7.Offset? position,
    _i7.Size? size,
    String? color,
    Map<String, _i2.NodeReference>? references,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createNode, [], {
              #title: title,
              #content: content,
              #position: position,
              #size: size,
              #color: color,
              #references: references,
              #metadata: metadata,
            }),
            returnValue: _i4.Future<_i2.Node>.value(
              _FakeNode_2(
                this,
                Invocation.method(#createNode, [], {
                  #title: title,
                  #content: content,
                  #position: position,
                  #size: size,
                  #color: color,
                  #references: references,
                  #metadata: metadata,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Node>.value(
              _FakeNode_2(
                this,
                Invocation.method(#createNode, [], {
                  #title: title,
                  #content: content,
                  #position: position,
                  #size: size,
                  #color: color,
                  #references: references,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Node>);

  @override
  _i4.Future<_i2.Node> updateNode(
    String? nodeId, {
    String? title,
    String? content,
    _i7.Offset? position,
    _i7.Size? size,
    _i2.NodeViewMode? viewMode,
    String? color,
    Map<String, _i2.NodeReference>? references,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateNode,
              [nodeId],
              {
                #title: title,
                #content: content,
                #position: position,
                #size: size,
                #viewMode: viewMode,
                #color: color,
                #references: references,
                #metadata: metadata,
              },
            ),
            returnValue: _i4.Future<_i2.Node>.value(
              _FakeNode_2(
                this,
                Invocation.method(
                  #updateNode,
                  [nodeId],
                  {
                    #title: title,
                    #content: content,
                    #position: position,
                    #size: size,
                    #viewMode: viewMode,
                    #color: color,
                    #references: references,
                    #metadata: metadata,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Node>.value(
              _FakeNode_2(
                this,
                Invocation.method(
                  #updateNode,
                  [nodeId],
                  {
                    #title: title,
                    #content: content,
                    #position: position,
                    #size: size,
                    #viewMode: viewMode,
                    #color: color,
                    #references: references,
                    #metadata: metadata,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Node>);

  @override
  _i4.Future<void> deleteNode(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNode, [nodeId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Node?> getNode(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getNode, [nodeId]),
            returnValue: _i4.Future<_i2.Node?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Node?>.value(),
          )
          as _i4.Future<_i2.Node?>);

  @override
  _i4.Future<List<_i2.Node>> getAllNodes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNodes, []),
            returnValue: _i4.Future<List<_i2.Node>>.value(<_i2.Node>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Node>>.value(
              <_i2.Node>[],
            ),
          )
          as _i4.Future<List<_i2.Node>>);

  @override
  _i4.Future<List<_i2.Node>> searchNodes(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchNodes, [query]),
            returnValue: _i4.Future<List<_i2.Node>>.value(<_i2.Node>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Node>>.value(
              <_i2.Node>[],
            ),
          )
          as _i4.Future<List<_i2.Node>>);

  @override
  _i4.Future<void> connectNodes({
    required String? fromNodeId,
    required String? toNodeId,
    required _i2.ReferenceType? type,
    String? role,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#connectNodes, [], {
              #fromNodeId: fromNodeId,
              #toNodeId: toNodeId,
              #type: type,
              #role: role,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disconnectNodes({
    required String? fromNodeId,
    required String? toNodeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectNodes, [], {
              #fromNodeId: fromNodeId,
              #toNodeId: toNodeId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> batchUpdate(List<_i6.NodeUpdate>? updates) =>
      (super.noSuchMethod(
            Invocation.method(#batchUpdate, [updates]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> batchDelete(List<String>? nodeIds) =>
      (super.noSuchMethod(
            Invocation.method(#batchDelete, [nodeIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [GraphService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphService extends _i1.Mock implements _i8.GraphService {
  @override
  _i4.Future<_i2.Graph> createGraph({
    required String? name,
    List<String>? nodeIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGraph, [], {
              #name: name,
              #nodeIds: nodeIds,
            }),
            returnValue: _i4.Future<_i2.Graph>.value(
              _FakeGraph_1(
                this,
                Invocation.method(#createGraph, [], {
                  #name: name,
                  #nodeIds: nodeIds,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Graph>.value(
              _FakeGraph_1(
                this,
                Invocation.method(#createGraph, [], {
                  #name: name,
                  #nodeIds: nodeIds,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Graph>);

  @override
  _i4.Future<_i2.Graph?> getGraph(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#getGraph, [graphId]),
            returnValue: _i4.Future<_i2.Graph?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Graph?>.value(),
          )
          as _i4.Future<_i2.Graph?>);

  @override
  _i4.Future<_i2.Graph?> getCurrentGraph() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentGraph, []),
            returnValue: _i4.Future<_i2.Graph?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Graph?>.value(),
          )
          as _i4.Future<_i2.Graph?>);

  @override
  _i4.Future<_i2.Graph> updateGraph(
    String? graphId, {
    String? name,
    List<String>? nodeIds,
    _i2.GraphViewConfig? viewConfig,
    Map<String, _i7.Offset>? nodePositions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateGraph,
              [graphId],
              {
                #name: name,
                #nodeIds: nodeIds,
                #viewConfig: viewConfig,
                #nodePositions: nodePositions,
              },
            ),
            returnValue: _i4.Future<_i2.Graph>.value(
              _FakeGraph_1(
                this,
                Invocation.method(
                  #updateGraph,
                  [graphId],
                  {
                    #name: name,
                    #nodeIds: nodeIds,
                    #viewConfig: viewConfig,
                    #nodePositions: nodePositions,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Graph>.value(
              _FakeGraph_1(
                this,
                Invocation.method(
                  #updateGraph,
                  [graphId],
                  {
                    #name: name,
                    #nodeIds: nodeIds,
                    #viewConfig: viewConfig,
                    #nodePositions: nodePositions,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Graph>);

  @override
  _i4.Future<void> deleteGraph(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGraph, [graphId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addNodeToGraph(String? graphId, String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#addNodeToGraph, [graphId, nodeId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeNodeFromGraph(String? graphId, String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#removeNodeFromGraph, [graphId, nodeId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Node>> getGraphNodes(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#getGraphNodes, [graphId]),
            returnValue: _i4.Future<List<_i2.Node>>.value(<_i2.Node>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Node>>.value(
              <_i2.Node>[],
            ),
          )
          as _i4.Future<List<_i2.Node>>);

  @override
  _i4.Future<List<_i2.Connection>> getGraphConnections(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#getGraphConnections, [graphId]),
            returnValue: _i4.Future<List<_i2.Connection>>.value(
              <_i2.Connection>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i2.Connection>>.value(
              <_i2.Connection>[],
            ),
          )
          as _i4.Future<List<_i2.Connection>>);

  @override
  _i4.Future<void> applyLayout(
    String? graphId,
    _i2.LayoutAlgorithm? algorithm,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyLayout, [graphId, algorithm]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> exportGraph(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#exportGraph, [graphId]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#exportGraph, [graphId]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#exportGraph, [graphId]),
              ),
            ),
          )
          as _i4.Future<String>);
}
