name: node_editor
version: 1.0.0
description: Markdown editor plugin for Node Graph Notebook.
publish_to: none
environment:
  sdk: '>=3.8.0 <4.0.0'
resolution: workspace
dependencies:
  flutter: { sdk: flutter }
  plugin:
    path: ../plugin
  flutter_bloc: ^9.1.1
  provider: ^6.1.1
  core: { path: ../core }
  appframe: { path: ../appframe }
  node_graph: { path: ../graph }
  flutter_markdown_plus: any
  flutter_markdown_plus_latex: any
  markdown: any
dev_dependencies:
  flutter_test: { sdk: flutter }
