name: node_i18n_en
version: 1.0.0
description: English language pack for Node Graph Notebook.
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core

  plugin: any
dev_dependencies:
  flutter_test:
    sdk: flutter
