// Mocks generated by Mockito 5.4.6 from annotations
// in node_graph_notebook/test/plugins/i18n/i18n_plugin_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:node_graph_notebook/core/commands/command_bus.dart' as _i3;
import 'package:node_graph_notebook/core/commands/models/command.dart' as _i2;
import 'package:node_graph_notebook/core/commands/models/command_handler.dart'
    as _i5;
import 'package:node_graph_notebook/core/commands/models/middleware.dart'
    as _i6;
import 'package:node_graph_notebook/core/events/app_events.dart' as _i8;
import 'package:node_graph_notebook/core/plugin/middleware/middleware_plugin.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCommandResult_0<T1> extends _i1.SmartFake
    implements _i2.CommandResult<T1> {
  _FakeCommandResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CommandBus].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommandBus extends _i1.Mock implements _i3.CommandBus {
  MockCommandBus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i3.CommandEvent> get commandStream =>
      (super.noSuchMethod(
            Invocation.getter(#commandStream),
            returnValue: _i4.Stream<_i3.CommandEvent>.empty(),
          )
          as _i4.Stream<_i3.CommandEvent>);

  @override
  void registerHandler<T extends _i2.Command<dynamic>>(
    _i5.CommandHandler<T>? handler,
    Type? commandType,
  ) => super.noSuchMethod(
    Invocation.method(#registerHandler, [handler, commandType]),
    returnValueForMissingStub: null,
  );

  @override
  void registerHandlers(
    Map<Type, _i5.CommandHandler<_i2.Command<dynamic>>>? handlers,
  ) => super.noSuchMethod(
    Invocation.method(#registerHandlers, [handlers]),
    returnValueForMissingStub: null,
  );

  @override
  void addMiddleware(_i6.CommandMiddleware? middleware) => super.noSuchMethod(
    Invocation.method(#addMiddleware, [middleware]),
    returnValueForMissingStub: null,
  );

  @override
  void addMiddlewarePlugin(_i7.CommandMiddlewarePlugin? middleware) =>
      super.noSuchMethod(
        Invocation.method(#addMiddlewarePlugin, [middleware]),
        returnValueForMissingStub: null,
      );

  @override
  void removeMiddlewarePlugin(_i7.CommandMiddlewarePlugin? middleware) =>
      super.noSuchMethod(
        Invocation.method(#removeMiddlewarePlugin, [middleware]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i2.CommandResult<T>> dispatch<T>(_i2.Command<T>? command) =>
      (super.noSuchMethod(
            Invocation.method(#dispatch, [command]),
            returnValue: _i4.Future<_i2.CommandResult<T>>.value(
              _FakeCommandResult_0<T>(
                this,
                Invocation.method(#dispatch, [command]),
              ),
            ),
          )
          as _i4.Future<_i2.CommandResult<T>>);

  @override
  _i4.Future<void> undo(_i2.Command<dynamic>? command) =>
      (super.noSuchMethod(
            Invocation.method(#undo, [command]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AppEventBus].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppEventBus extends _i1.Mock implements _i8.AppEventBus {
  MockAppEventBus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i8.AppEvent> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i8.AppEvent>.empty(),
          )
          as _i4.Stream<_i8.AppEvent>);

  @override
  set onError(void Function(_i8.AppEvent?, Object, StackTrace)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onError, value),
        returnValueForMissingStub: null,
      );

  @override
  void publish(_i8.AppEvent? event) => super.noSuchMethod(
    Invocation.method(#publish, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
