name: node_converter
version: 1.0.0
description: Import/export converter plugin for Node Graph Notebook.
publish_to: none
environment:
  sdk: '>=3.8.0 <4.0.0'
resolution: workspace
dependencies:
  core_data:
    path: ../core_data
  flutter: { sdk: flutter }
  flutter_bloc: ^9.1.1
  provider: ^6.1.1
  equatable: ^2.0.5
  core: { path: ../core }
  appframe: { path: ../appframe }
  node_graph: { path: ../graph }
  node_ai: any
  uuid: any
  path: any
  path_provider: any
  file_picker: any
  node_editor: any
  plugin: any
dev_dependencies:
  flutter_test: { sdk: flutter }
