// Mocks generated by Mockito 5.4.6 from annotations
// in node_graph_notebook/test/bloc/graph/graph_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:node_graph_notebook/core/models/models.dart' as _i2;
import 'package:node_graph_notebook/core/services/commands/command.dart' as _i8;
import 'package:node_graph_notebook/core/services/graph_service.dart' as _i3;
import 'package:node_graph_notebook/core/services/undo_manager.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGraph_0 extends _i1.SmartFake implements _i2.Graph {
  _FakeGraph_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GraphService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphService extends _i1.Mock implements _i3.GraphService {
  @override
  _i4.Future<_i2.Graph> createGraph({
    required String? name,
    List<String>? nodeIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGraph, [], {
              #name: name,
              #nodeIds: nodeIds,
            }),
            returnValue: _i4.Future<_i2.Graph>.value(
              _FakeGraph_0(
                this,
                Invocation.method(#createGraph, [], {
                  #name: name,
                  #nodeIds: nodeIds,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Graph>.value(
              _FakeGraph_0(
                this,
                Invocation.method(#createGraph, [], {
                  #name: name,
                  #nodeIds: nodeIds,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Graph>);

  @override
  _i4.Future<_i2.Graph?> getGraph(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#getGraph, [graphId]),
            returnValue: _i4.Future<_i2.Graph?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Graph?>.value(),
          )
          as _i4.Future<_i2.Graph?>);

  @override
  _i4.Future<_i2.Graph?> getCurrentGraph() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentGraph, []),
            returnValue: _i4.Future<_i2.Graph?>.value(),
            returnValueForMissingStub: _i4.Future<_i2.Graph?>.value(),
          )
          as _i4.Future<_i2.Graph?>);

  @override
  _i4.Future<_i2.Graph> updateGraph(
    String? graphId, {
    String? name,
    List<String>? nodeIds,
    _i2.GraphViewConfig? viewConfig,
    Map<String, _i5.Offset>? nodePositions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateGraph,
              [graphId],
              {
                #name: name,
                #nodeIds: nodeIds,
                #viewConfig: viewConfig,
                #nodePositions: nodePositions,
              },
            ),
            returnValue: _i4.Future<_i2.Graph>.value(
              _FakeGraph_0(
                this,
                Invocation.method(
                  #updateGraph,
                  [graphId],
                  {
                    #name: name,
                    #nodeIds: nodeIds,
                    #viewConfig: viewConfig,
                    #nodePositions: nodePositions,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Graph>.value(
              _FakeGraph_0(
                this,
                Invocation.method(
                  #updateGraph,
                  [graphId],
                  {
                    #name: name,
                    #nodeIds: nodeIds,
                    #viewConfig: viewConfig,
                    #nodePositions: nodePositions,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Graph>);

  @override
  _i4.Future<void> deleteGraph(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGraph, [graphId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addNodeToGraph(String? graphId, String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#addNodeToGraph, [graphId, nodeId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeNodeFromGraph(String? graphId, String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#removeNodeFromGraph, [graphId, nodeId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Node>> getGraphNodes(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#getGraphNodes, [graphId]),
            returnValue: _i4.Future<List<_i2.Node>>.value(<_i2.Node>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Node>>.value(
              <_i2.Node>[],
            ),
          )
          as _i4.Future<List<_i2.Node>>);

  @override
  _i4.Future<List<_i2.Connection>> getGraphConnections(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#getGraphConnections, [graphId]),
            returnValue: _i4.Future<List<_i2.Connection>>.value(
              <_i2.Connection>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i2.Connection>>.value(
              <_i2.Connection>[],
            ),
          )
          as _i4.Future<List<_i2.Connection>>);

  @override
  _i4.Future<void> applyLayout(
    String? graphId,
    _i2.LayoutAlgorithm? algorithm,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyLayout, [graphId, algorithm]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> exportGraph(String? graphId) =>
      (super.noSuchMethod(
            Invocation.method(#exportGraph, [graphId]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#exportGraph, [graphId]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#exportGraph, [graphId]),
              ),
            ),
          )
          as _i4.Future<String>);
}

/// A class which mocks [UndoManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockUndoManager extends _i1.Mock implements _i7.UndoManager {
  @override
  bool get canUndo =>
      (super.noSuchMethod(
            Invocation.getter(#canUndo),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get canRedo =>
      (super.noSuchMethod(
            Invocation.getter(#canRedo),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> execute(_i8.Command? command) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [command]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> undo() =>
      (super.noSuchMethod(
            Invocation.method(#undo, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> redo() =>
      (super.noSuchMethod(
            Invocation.method(#redo, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
