// Mocks generated by Mockito 5.4.6 from annotations
// in node_graph_notebook/test/plugins/folder/ui/folder_tree_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i12;

import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:node_graph_notebook/core/models/models.dart' as _i4;
import 'package:node_graph_notebook/plugins/graph/bloc/graph_bloc.dart' as _i9;
import 'package:node_graph_notebook/plugins/graph/bloc/graph_event.dart'
    as _i10;
import 'package:node_graph_notebook/plugins/graph/bloc/graph_state.dart' as _i3;
import 'package:node_graph_notebook/plugins/graph/bloc/node_bloc.dart' as _i5;
import 'package:node_graph_notebook/plugins/graph/bloc/node_event.dart' as _i7;
import 'package:node_graph_notebook/plugins/graph/bloc/node_state.dart' as _i2;
import 'package:node_graph_notebook/plugins/graph/service/node_service.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNodeState_0 extends _i1.SmartFake implements _i2.NodeState {
  _FakeNodeState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGraphState_1 extends _i1.SmartFake implements _i3.GraphState {
  _FakeGraphState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNode_2 extends _i1.SmartFake implements _i4.Node {
  _FakeNode_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NodeBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeBloc extends _i1.Mock implements _i5.NodeBloc {
  MockNodeBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NodeState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeNodeState_0(this, Invocation.getter(#state)),
          )
          as _i2.NodeState);

  @override
  _i6.Stream<_i2.NodeState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i2.NodeState>.empty(),
          )
          as _i6.Stream<_i2.NodeState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i7.NodeEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i7.NodeEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.NodeState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i7.NodeEvent>(
    _i8.EventHandler<E, _i2.NodeState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(_i8.Transition<_i7.NodeEvent, _i2.NodeState>? transition) =>
      super.noSuchMethod(
        Invocation.method(#onTransition, [transition]),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i8.Change<_i2.NodeState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GraphBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphBloc extends _i1.Mock implements _i9.GraphBloc {
  MockGraphBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GraphState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeGraphState_1(this, Invocation.getter(#state)),
          )
          as _i3.GraphState);

  @override
  _i6.Stream<_i3.GraphState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i3.GraphState>.empty(),
          )
          as _i6.Stream<_i3.GraphState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void add(_i10.GraphEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i10.GraphEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.GraphState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i10.GraphEvent>(
    _i8.EventHandler<E, _i3.GraphState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i8.Transition<_i10.GraphEvent, _i3.GraphState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i8.Change<_i3.GraphState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NodeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeService extends _i1.Mock implements _i11.NodeService {
  MockNodeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Node> createNode({
    required String? title,
    String? content,
    _i12.Offset? position,
    _i12.Size? size,
    String? color,
    Map<String, _i4.NodeReference>? references,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createNode, [], {
              #title: title,
              #content: content,
              #position: position,
              #size: size,
              #color: color,
              #references: references,
              #metadata: metadata,
            }),
            returnValue: _i6.Future<_i4.Node>.value(
              _FakeNode_2(
                this,
                Invocation.method(#createNode, [], {
                  #title: title,
                  #content: content,
                  #position: position,
                  #size: size,
                  #color: color,
                  #references: references,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Node>);

  @override
  _i6.Future<_i4.Node> updateNode(
    String? nodeId, {
    String? title,
    String? content,
    _i12.Offset? position,
    _i12.Size? size,
    _i4.NodeViewMode? viewMode,
    String? color,
    Map<String, _i4.NodeReference>? references,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateNode,
              [nodeId],
              {
                #title: title,
                #content: content,
                #position: position,
                #size: size,
                #viewMode: viewMode,
                #color: color,
                #references: references,
                #metadata: metadata,
              },
            ),
            returnValue: _i6.Future<_i4.Node>.value(
              _FakeNode_2(
                this,
                Invocation.method(
                  #updateNode,
                  [nodeId],
                  {
                    #title: title,
                    #content: content,
                    #position: position,
                    #size: size,
                    #viewMode: viewMode,
                    #color: color,
                    #references: references,
                    #metadata: metadata,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Node>);

  @override
  _i6.Future<void> deleteNode(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNode, [nodeId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.Node?> getNode(String? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getNode, [nodeId]),
            returnValue: _i6.Future<_i4.Node?>.value(),
          )
          as _i6.Future<_i4.Node?>);

  @override
  _i6.Future<List<_i4.Node>> getAllNodes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNodes, []),
            returnValue: _i6.Future<List<_i4.Node>>.value(<_i4.Node>[]),
          )
          as _i6.Future<List<_i4.Node>>);

  @override
  _i6.Future<List<_i4.Node>> searchNodes(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchNodes, [query]),
            returnValue: _i6.Future<List<_i4.Node>>.value(<_i4.Node>[]),
          )
          as _i6.Future<List<_i4.Node>>);

  @override
  _i6.Future<void> connectNodes({
    required String? fromNodeId,
    required String? toNodeId,
    Map<String, dynamic>? properties,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#connectNodes, [], {
              #fromNodeId: fromNodeId,
              #toNodeId: toNodeId,
              #properties: properties,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> disconnectNodes({
    required String? fromNodeId,
    required String? toNodeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectNodes, [], {
              #fromNodeId: fromNodeId,
              #toNodeId: toNodeId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> batchUpdate(List<_i11.NodeUpdate>? updates) =>
      (super.noSuchMethod(
            Invocation.method(#batchUpdate, [updates]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> batchDelete(List<String>? nodeIds) =>
      (super.noSuchMethod(
            Invocation.method(#batchDelete, [nodeIds]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, int>> calculateNodeDepths(List<_i4.Node>? nodes) =>
      (super.noSuchMethod(
            Invocation.method(#calculateNodeDepths, [nodes]),
            returnValue: _i6.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i6.Future<Map<String, int>>);
}
